#!/usr/bin/env bash
# A factors challenge

check_factor()
{
        if [ $# -ne 3 ];
        then
                args=("$@")
                count=0
                y=1
                for a in "${args[@]}";
                do
                        if [ $count -gt 1 ];
                        then
                                y=$(echo "$a * $y" | bc)
                        fi
                        count=$((count + 1))
                done
        else
                y=$3
        fi

        x=$2
        num=$(echo "$1" | tr ':' '=')

        result=$(echo "if($y > $x) 1 else 0" | bc)
   if ((result == 1)); then
                ycp=$x
                x=$y
                y=$ycp
        fi

        echo "$num$x * $y"
}

if [ $# -ne 1 ]
then
        echo 'Usage: factors <file>'
        exit 1
else
        while read i
        do
                result=$(factor "$i")
                check_factor $result
        done < "$1"
fi
