#!/usr/bin/env bash
# is a challenge

check_factor()
{
        if [ $# -ne 3 ]; then
                parameters=("$@")
                counter=0
                y=1
                for element in ${parameters[*]}; do
                        if [ $counter -gt 1 ]; then
                                y=$(echo "$element * $y" | bc)
                        fi
                        counter=$((counter + 1))
                done
        else
                y=$3
        fi

        x=$2
        equation=$(echo "$1" | tr ':' '=')

        outcome=$(echo "if($y > $x) 1 else 0" | bc)
        if ((outcome == 1)); then
                temp=$x
                x=$y
	  	y=$temp
	fi

        echo "$equation$x*$y"
}

	if [ $# -ne 1 ]; then
        	echo 'Usage: rsa <file>'
        exit 1
		else
        while read i; do
                result=$(factor "$i")
                check_factor $result
        done < "$1"
fi
